name: lab4d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch==2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - torchvision
  - cudatoolkit-dev=11.7
  - gcc_linux-64=11
  - gxx_linux-64=11
  - matplotlib
  - ninja
  - absl-py 
  - tensorboard 
  - trimesh 
  - scikit-image
  - opencv 
  - einops 
  - numba 
  - gdown 
  - scikit-learn 
  - psutil 
  - av 
  - plotly
  - imageio
  - imageio-ffmpeg
  - tqdm
  - pip:
    - pysdf
    - gradio==3.49.0
    - timm==0.6.7
    - detectron2 @ git+https://github.com/facebookresearch/detectron2.git
    - segment_anything @ git+https://github.com/facebookresearch/segment-anything.git
    - groundingdino @ git+https://github.com/IDEA-Research/GroundingDINO.git
    - openmim
    - pyrender
