name: agent2sim
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - setuptools=66.0.0
  - pip
  - pytorch==2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - torchvision=0.15.0
  - cudatoolkit-dev=11.7
  - gcc_linux-64=10
  - gxx_linux-64=10
  - matplotlib
  - ninja
  - absl-py 
  - tensorboard 
  - trimesh 
  - scikit-image
  - opencv 
  - einops 
  - numba 
  - gdown 
  - scikit-learn 
  - psutil 
  - av 
  - plotly
  - imageio
  - imageio-ffmpeg
  - tqdm
  - pip:
    - gradio==3.49.0
    - timm==0.6.7
    - detectron2 @ git+https://github.com/facebookresearch/detectron2.git@e9f7e2b
    - segment_anything @ git+https://github.com/facebookresearch/segment-anything.git
    - groundingdino @ git+https://github.com/IDEA-Research/GroundingDINO.git
    - chumpy @ git+https://github.com/scottandrews/chumpy.git@fe51783e0364bf1e9b705541e7d77f894dd2b1ac
    - gsplat @ git+https://github.com/gengshan-y/gsplat-dev
    - viser @ git+https://github.com/gengshan-y/viser-dev
    - torchcubicspline @ git+https://github.com/patrick-kidger/torchcubicspline.git
    - urdfpy @ git+https://github.com/mmatl/urdfpy
    - openmim
    - pyrender
    - open3d==0.17.0
    - geomloss==0.2.6
    - point-cloud-utils==0.30.0
    - diffusers==0.27.2
    - pytorch-lightning==2.2.5
    - smplx==0.1.28
    - openexr
    - recordclass
    - celluloid
    - networkx==2.5
